--- 
# Install Docker
- hosts: docker
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install pre-reqs
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
      - apt-transport-https
      - ca-certificates
      - python-pip
    - name: Installing Docker-Py
      pip: name={{ item }} state=latest
      with_items:
      - docker-py
    - name: Add GPG key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
    - name: Create docker.list file
      raw: touch /etc/apt/sources.list.d/docker.list
    - name: Add repo
      raw: echo 'deb https://apt.dockerproject.org/repo ubuntu-wily main' > /etc/apt/sources.list.d/docker.list
    - name: Install Docker Engine
      apt: pkg=docker-engine state=latest update_cache=true
    - name: Start Docker Service
      service: name=docker state=started
    - name: add user to docker group
      user: name=vagrant group=docker append=yes
    - name: run container hello-world
      docker: name=hello-world image=hello-world state=started 
